version: '3.9'
services:
    django:
        build: .
        container_name: django
        command: /usr/src/app/docker/start.sh
        volumes:
          - ../:/usr/src/app
        ports:
          - 8000:8000
        depends_on:
          - pgdb
  
    pgdb:
        image: postgres
        container_name: pgdb
        volumes:
            - ../db_data:/var/lib/postgresql/data 
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"

volumes:
  db_data:
     external: true 

# docker compose run django django-admin startproject RateMyPic .
# docker compose up
# docker compose up -d --build --> changing the new features