services:
  django:
    build: .
    container_name: django
    command: /usr/src/app/docker/start.sh
    volumes:
      - ../:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb
    env_file:
      - .env
    networks:
      mynetwork:
         ipv4_address: 172.21.0.5

  pgdb:
    image: postgres
    container_name: pgdb
    volumes:
      - db_data:/var/lib/postgresql/data 
    env_file:
      - .env
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 8080:80
    depends_on:
      - pgdb
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - mynetwork

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - scraper
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:r


  scraper:
    image: scraper
    container_name: scraper
    user: user
    build:
      context: ../Crawler
      dockerfile: Dockerfile
    depends_on:
      - pgdb
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.scraper.schedule: "@every 1m"
      ofelia.job-exec.scraper.command: "python crawler.py"
    
    volumes:
      - ../Images:/usr/src/app/cache_images 
    networks: 
      - mynetwork

volumes:
  db_data:
  pgadmin-data:


networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16


