# Generated by Django 5.0.7 on 2024-08-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_image_id', models.CharField()),
                ('publisher_id', models.CharField()),
                ('published_date', models.DateField()),
                ('liked_count', models.IntegerField()),
                ('disliked_count', models.IntegerField()),
            ],
        ),
    ]
