# Generated by Django 5.0.7 on 2024-08-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'MetaData', 'verbose_name_plural': 'MetaData'},
        ),
    ]
