# Generated by Django 5.0.7 on 2024-08-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0002_alter_metadata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={},
        ),
    ]
