# Generated by Django 5.0.7 on 2024-08-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0003_alter_metadata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='hashed_image_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='publisher_id',
            field=models.CharField(max_length=255),
        ),
    ]
