# Generated by Django 5.0.7 on 2024-08-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0004_alter_metadata_hashed_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='hashed_image_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
