# Generated by Django 5.0.7 on 2024-08-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0005_alter_metadata_hashed_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
