# Generated by Django 5.0.7 on 2024-08-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0006_alter_metadata_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='disliked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='liked_count',
            field=models.IntegerField(default=0),
        ),
    ]
