# Generated by Django 5.0.7 on 2024-08-09 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0007_alter_metadata_disliked_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='published_date',
            field=models.DateField(default=datetime.date(2024, 8, 9)),
        ),
    ]
